### ISSUE TITLE
Ceilometer

### ISSUE THREAD

**Issue by tranma** [anchor/borel-core#17]
Part of an effort to clean up Borel et al.

The Ceilometer part in this codebase is its own beast and deals with a lot of voodoo parsing. See: https://github.com/anchor/borel-core/blob/master/lib/Borel/Aggregate/Ceilometer/Consolidated/Query.hs

Is it possible to split it into a separate package for anyone who wants to deal with Ceilometer? I think it should be possible to make such a package Borel-agnostic. Then this repo (borel-core) won't be very useful but we can make it only contain OpenStack types and top-level queries.

Does this make sense, @fractalcat @oswynb ?

**Comment by oswynb** [comment]
So I think splitting off the Ceilometer stuff is definitely a good idea, but we should make that contain the types as well (as well as a rewrite of said types). I want to leverage the Iso/Prism stuff that @christian-marie demonstrated in https://github.com/anchor/roundtrip-aeson.

We would have one Iso per metric type: cpuIso, diskIso, etc. Then the collector, which currently does converts JSON -> SimplePoint would be slightly modified to instead convert JSON -> CeilometerPoint and then as part of writing to spool files would (decode/unapply) from the CeilometerPoint to SimplePoint.

borel would then simply have to call the appropriate iso to (encode/apply) from the SimplePoint to the appropriate CeilometerPoint (we can figure out which one to use from the SourceDict). All metering/billing logic would then be done on CeilometerPoints, without needing to deal with knowing that decode 4 :: InstancePoint is an instance-super-enormous or that decode 7 :: InstancePoint is an instance-special-instance-size-for-bob.

(encode/decode direction doesn't matter, it's an Iso, Ceilo->Simple could be encode or decode, it really doesn't matter and the types will ensure we go the right way)

Benefits:

Conversion between Vault format and Logic format would be unified. If we want to modify this then we only need to do it in one place rather than two (borel + vaultaire-collector-ceilometer).

It's easier to ensure that encoding matches decoding. It is easier to find bugs if we have encodeInstanceStatus "running" = InstanceRunning instead of encodeIstanceStatus "running" = 4, and then checking if in borel that decodeInstanceStatus 4 = InstanceRunning. All the logic would be in the format of :

instanceIso :: Iso SimplePoint (CeilometerPoint CPU Cumulative Pollster)
instanceIso = Iso { apply     (SimplePoint addr ts v) = Just $ CPUPoint addr ts v
                          , unapply (CPUPoint addr ts v)     = Just $ SimplePoint addr ts v
                          }

Thoughts? @fractalcat @tranma

**Comment by tranma** [comment]
That's fine. The metering/billing logic (that will operate on CeilometerPoint) can stay in this package, but it needs to be rewritten completely.

Can you whip up a prototype ceilometer package that unifies "collector" and - er, I dunno, "dellector" parts of Ceilometer first?

**Comment by oswynb** [comment]
anchor-ceilometer-common a suitable name? @fractalcat

**Comment by fractalcat** [comment]
I'd go for `ceilometer-common` personally.

**Comment by tranma** [comment]
done in 0.16.0
